Convert map to list
Odin-SMR/odin-level0-lambda pull request #4
Opened 2023-09-15 08:36 UTC by skymandr

This makes it possible to import SHK files (python 2 vs. python 3 error).

2023-09-15 10:07 UTC, Baapity requested changes

2023-09-15 10:07 UTC, Baapity commented on level0/import_l0/handler/import_level0.py
> +        data1 = np.array(list(map(table[2], data[1])))
```suggestion
        data1 = np.array([table[2](x) for x in data[1]])
```

2023-09-15 10:07 UTC, Baapity commented on level0/import_l0/handler/import_level0.py
> +        data1 = np.array(list(map(table[2], data[1])))
Should do the same thing, removing the usage of list & map

2023-09-15 10:11 UTC, Baapity approved these changes

2023-09-15 10:26 UTC, Baapity approved these changes
:shipit:

2023-09-21 09:08 UTC, joakimmoller approved these changes

2023-09-21 09:55 UTC, merged